a = int(input('Enter the Number:'))
b = int(input('Enter the Number:'))
print('The Value of' ,a, " + ",b, 'is:',a + b)
print('The Value of' ,a, " - ",b, 'is:',a - b)
print('The Value of' ,a, " * ",b, 'is:',a * b)
print('The Value of' ,a, " / ",b, 'is:',a / b)
print('The Value of' ,a, " % ",b, 'is:',a % b)
print('The Value of' ,a, " // ",b, 'is:',a // b)
print('The Value of' ,a, " ** ",b, 'is:',a ** b)

